### ISSUE TITLE
Key Error, How do I fix it? 

### ISSUE THREAD

**Issue by ensenas85** [JUSTadICE-CHaN/JUSTaMudaeBot#5]
![Screenshot 2024-09-26 045238](https://github.com/user-attachments/assets/8c3ec13c-b854-415d-9c29-911f559a26ee)

**Comment by ensenas85** [comment]
How do I even start the bot?

**Comment by ensenas85** [comment]
Do you have Discord? I'm willing to pay to get this to work for me. @JUSTadICE-CHaN

**Comment by TarotOfficial** [comment]
Are you sure you wrote the key and ids correctly? Try to write /help and send mudae bot a message.

**Comment by ensenas85** [comment]
Pretty sure I did, but how do I start this self bot?

**Comment by TarotOfficial** [comment]
> Pretty sure I did, but how do I start this self bot?

download python 3.10, open config.py and wrote your things. After then go to your server type /help. Mudae will send you message write him few message and open your normal.py file.

**Comment by ensenas85** [comment]
![image](https://github.com/user-attachments/assets/ac566434-9da0-4493-bff6-b6b18322373f)
Yeah I did that and all tried to run it and this error pops up?

**Comment by ensenas85** [comment]
Pretty sure I'm messing up the channel ID thingy as I don't know where exactly to put the channel ID, so if you can like post a screenshot of ane xample that would be helpful.

**Comment by TarotOfficial** [comment]
> Pretty sure I'm messing up the channel ID thingy as I don't know where exactly to put the channel ID, so if you can like post a screenshot of ane xample that would be helpful.

![image](https://github.com/user-attachments/assets/581a5f59-4545-4bcd-9a9b-3cfa63e63866)
Servers[11111111] is server id
Channels
1: [1.1, 1,2] in here 1 is main channel where you enter your rolling, $dk and $daily things. 1.1 and 1.2 is subchannel ids for just monitoring and sniping it should be in same server channels.
I think you know other things so i will skip them.
After your server and channel ids you should send /help command in your server and type mudae bot a message.
If u using more accounts or something check your token if its correct.

**Comment by JUSTadICE-CHaN** [comment]
im marking this as resolved as it seemed to just be a token input thingy
