### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by 8percxnt** [JUSTadICE-CHaN/JUSTaMudaeBot#7]
Hello there, I have a problem. The server that I am on is French and Mudae's language is also in French. And when I run Normal.py I get parse error. Can you help me ( im not good at coding )

**Comment by JUSTadICE-CHaN** [comment]
send your $tu message reply from mudae

**Comment by 8percxnt** [comment]
> send your $tu message reply from mudae 

Here : hyra666, vous pouvez vous marier dès maintenant ! Le prochain reset est dans 57 min. Vous avez 8 rolls restants. Prochain rolls reset dans 57 min. Prochain $daily reset dans 9h 18 min. Vous pouvez réagir aux kakera dès maintenant ! Power: 100% Chaque réaction à un kakera consomme 100% de votre pouvoir de réaction. Vos personnages possédant 10+ keys consomment moitié moins de pouvoir (50%) Stock: 265:kakera: Prochain $dk reset dans 9h 18 min. Vous pourrez revoter dans environ 5h 05 min. => $tuarrange

**Comment by JUSTadICE-CHaN** [comment]
as a screenshot please

**Comment by 8percxnt** [comment]
> as a screenshot please

There you go ![image](https://github.com/user-attachments/assets/58215d42-130a-4097-bbff-16b9aa0098ea)

**Comment by 8percxnt** [comment]
Add me on discord it's easier to communicate

**Comment by 8percxnt** [comment]
This is when I don't have my marry ![image](https://github.com/user-attachments/assets/46f28000-9409-4c7c-a1ed-1b8440e3562c) couldn't be helpful idk

**Comment by 8percxnt** [comment]
> as a screenshot please

Add me on discord (hyra666) it's easier to communicate

**Comment by JUSTadICE-CHaN** [comment]
Unfortunately the bot does not working when mudae is set to other languages. If you want to make it so you'll have to edit the actual code in normal.py, sorry.

**Comment by 8percxnt** [comment]
> Unfortunately the bot does not work when mudae is set to other languages. If you want to make it so you'll have to edit the actual code in normal.py, sorry.

Do you know what part of the code I should rewrite? Or should I rewrite the whole script

**Comment by JUSTadICE-CHaN** [comment]
I need the whole error log

**Comment by 8percxnt** [comment]
> I need the whole error log

Here: ![image](https://github.com/user-attachments/assets/ecb137ed-6a02-47c6-a93f-f9f06f58a569)

PS C:\Users\Nisha\Downloads\JUSTaMudaeBot-main1> python Normal.py
Traceback (most recent call last):
  File "C:\Users\Nisha\Downloads\JUSTaMudaeBot-main1\Normal.py", line 320, in <module>
    client = MyClient()
             ^^^^^^^^^^
  File "C:\Users\Nisha\Downloads\JUSTaMudaeBot-main1\Normal.py", line 21, in __init__
    super().__init__()
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'
PS C:\Users\Nisha\Downloads\JUSTaMudaeBot-main1>

**Comment by JUSTadICE-CHaN** [comment]
That looks like a python or required libraries error, what python version do you have?

**Comment by 8percxnt** [comment]
> That looks like a python or required libraries error, what python version do you have?

I think I have the latest version. Also before you updated the script it was working

**Comment by JUSTadICE-CHaN** [comment]
i added u
