### ISSUE TITLE
Kakera value

### ISSUE THREAD

**Issue by rebigon** [JUSTadICE-CHaN/JUSTaMudaeBot#8]
I finded out this issue, when kakera value is disabled on server. He can't also claim waifus/wishes with this problem. Is there any fix to this?

![373984030-aaecdec9-3d92-4aea-bc5f-89f3cd3aa8c6](https://github.com/user-attachments/assets/ac6d449c-b558-4819-99fb-129c8b154144)

**Comment by JUSTadICE-CHaN** [comment]
Thats just saying that your config file doesnt have a delay, show me your config file

**Comment by rebigon** [comment]
> Thats just saying that your config file doesnt have a delay, show me your config file

![image](https://github.com/user-attachments/assets/5435e132-23d3-4025-b2e8-bd8b289d1b1f)

**Comment by rebigon** [comment]
I added delay and now I'm seeing this 

![image](https://github.com/user-attachments/assets/74da84d5-2dfc-4871-9a21-733a504691c1)

**Comment by JUSTadICE-CHaN** [comment]
Hmm Ill try and edit the bot so that it works with none values, but its not meant to to be honest

**Comment by rebigon** [comment]
Thank you so much, I appreciate that. Sorry for bothering tho

**Comment by JUSTadICE-CHaN** [comment]
should be fixed with the latest release
